### ISSUE TITLE
when we put blank to inFilter we get no data.

### ISSUE THREAD

**Issue by phalsopheak** [supabase/supabase-flutter#1007]
![code](https://github.com/user-attachments/assets/e1f650df-3a23-46da-8e88-1dc04f27d697)

I have a page to filter purchase order by Date, UserId, SupplierId..

When user pick a few supplier , I will get all data by supplier it is work fine. 
but when user pick all for User or Supplier I want to get all user, supplier.

If inFilter support null value to return all row it will help a lot.

Thanks.

**Comment by dshukertjr** [comment]
Hi there,

Thanks for the suggestion! Although at first glance it may sound useful to access `null` value as  the value for `inFilter` to just return everything, the behavior differs from that of Postgres. 

The goal of PostgREST and the Supabase client library is to create an experience where it feels like you are directly querying the Postgres database from your client. Because of that, we strive to match the behavior of our client libraries as much as possible to Postgres. 

What you can do in your case is to conditionally apply the filters. 

```dart
final query = supabase.from('table').eq('col', 1);
if(certainCondition) query = query.inFilter('anotherCol', [1, 2, 3]);
```
