### ISSUE TITLE
Client side cache for offline data query

### ISSUE THREAD

**Issue by iriealex** [supabase/supabase-flutter#140]
With Firebase, when you make a change to a document, the document is automatically saved locally (in order to quickly update the views of the application) but this is not the case with Supabase (to my awareness).

Isn't there an existing system to do this or should we code it ourselves? Claiming to be a Firebase alternative, shouldn't this feature be one of the most basic to have been implemented?

**Comment by dshukertjr** [comment]
I wanted to link this issue to the following Github Discussions where they discuss offline support of Supabase. 

https://github.com/supabase/supabase/discussions/357

**Comment by iriealex** [comment]
Ok. Let's do it!

**Comment by dshukertjr** [comment]
Realistically speaking, it will take a while until we can bring this to Supabase, but it would for sure be an awesome feature to have. It turns out conflict resolutions in SQL database is very hard. Most of the databases out there that offer offline support are NoSQL database. That being said, we are constantly exploring options to bring this feature to Supabase!

**Comment by iriealex** [comment]
Thanks for the feedback!

**Comment by dshukertjr** [comment]
Just wanted to come back to this issue. Currently, Supabase's features require an internet connection in order to provide data. If the device goes offline, client cannot simply get data. This is a known limitation of Supabase, and we do have some attempts to solve it like [this one](https://supabase.com/blog/postgres-crdt). Until we find a proper fix for offline support across all Supabase producets, Supabase will remain to have a stable internet connection as a requirement. With this, I will close this issue for now.
