### ISSUE TITLE
Reset password generates 3 onAuthState changes. 

### ISSUE THREAD

**Issue by JulianSwales** [supabase/supabase-flutter#184]
1.0.0-dev-3
I'm wondering if this is correct. When I generate a resetPasswordForEmail, it send me the reset deep link. 
When I click on that link, I get three onAuthStateChange events. 
signedIn followed by passwordRecovery followed by signedIn.
Why am I getting the signedIn states?  It's I'm watching for signed in as well as password recovery is getting tricky to react to a given state, unless this is expected? 
I'm watching client.auth.onAuthStateChange((event, session) {});

**Comment by yukiyamazaki** [comment]
Has this problem been resolved?
I have the same problem.

**Comment by Vinzent03** [comment]
I can't reproduce the issue on `v1.5.2`. I get an `signedIn` event followed by `passwordRecovery`. Depending on your JWT expiry limit and the time you open the link it may be caused by the jwt refreshing, but this should have an `tokenRefreshed` event before that.

Please comment or open a new issue if you still encounter this issue.
