### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by bdlukaa** [supabase/supabase-flutter#233]
In order to keep track of performance, we need to add some benchmarks to the client.

- [ ] Postgrest
- [ ] Auth
- [ ] Storage
- [ ] Functions
- [ ] Realtime

**Additional context**
- https://api.flutter.dev/flutter/flutter_test/benchmarkWidgets.html
- https://api.flutter.dev/flutter/flutter_test/WidgetTester/pumpBenchmark.html
- https://docs.flutter.dev/cookbook/testing/integration/profiling
- https://github.com/flutter/flutter/blob/master/dev/benchmarks/macrobenchmarks/test/util.dart

**Comment by dshukertjr** [comment]
So would this pretty much be just adding some additional test cases in each libraries?

**Comment by Vinzent03** [comment]
I don't know what performance we really want to measure. I think all libraries just pass the configuration to an http call. Beside json en/decoding, there isn't much computation. I think to test isolates the test have to run on real mobile devices, because the isolates performance is very different from desktop.

**Comment by Vinzent03** [comment]
In addition, not only execution time is important for isolates, because the isolate is always slower, but we want to keep the max frame rate on Flutter in the main root isolate, right? I think this needs an integration test.

**Comment by dshukertjr** [comment]
I think we don't have the time and resources to create a nice set of benchmarks for this library, so I'm closing this one. It was a great idea though.
