### ISSUE TITLE
Reset password redirect does not work on mobile and desktop

### ISSUE THREAD

**Issue by Sesa1988** [supabase/supabase-flutter#273]
I have basically the same configuration as in this issue (https://github.com/supabase/supabase-flutter/issues/261) and tested this on Android.

In addition Im calling the following

```
@override
  Future<void> resetEmailPassword(String email) async {
    await _supabaseClientService.get().auth.resetPasswordForEmail(
          email,
          redirectTo:
              'com.sesa.cryptowulf.${EnvironmentHelper.envName}://callback',
        );
  }
```

Im not sure how to detect if there is an authentication callback or a reset password callback but I don't get a redirect and the browser tries to redirect to localhost:3000 instead of my provided redirectTo url.

Maybe its a similar issue?

**Comment by dshukertjr** [comment]
Hmm, `redirectTo` seems to be working correct for me, and I can redirect back to my app using Android. Would you be able to check the version of gotrue you are using by opening pubspec.lock file? If it is above 1.1.0, it should be fine.

In order to detect a password recovery, you can check the auth event to see if it is `AuthChangeEvent.passwordRecovery`.
```dart
supabase.auth.onAuthStateChange.listen((data) {
  if(data.event == AuthChangeEvent.passwordRecovery) {
    // handle password recovery here
  }
});
```

**Comment by Sesa1988** [comment]
Update from 1.1.0 to latest gotrue fixed this issue.
