### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by matthewwong525** [supabase/supabase-flutter#278]
I want my flutter app (that uses supabase) to have linux support.

When can we expect linux support or will it never come?

**Additional context**
I searched around and couldn't find anything regarding the timeline of when Linux support will happen and the level of effort it takes to get to it. I also noticed in the chart on pub dev that Linux doesn't have null safety for the Provider Auth.
![image](https://user-images.githubusercontent.com/20890995/202563109-e45b0c9f-49a9-487d-9191-9968a2aab932.png)

**Comment by Vinzent03** [comment]
The issue is missing deep link support for Linux. There is an open issue in the package: https://github.com/llfbandit/app_links/issues/20

**Comment by dshukertjr** [comment]
@matthewwong525 

You can use most of the features on Linux today actually. All that is missing is the deep link feature to bring back the user to the app once someone clicks on the confirmation email as @Vinzent03 has pointed out. Everything else from database, realtime, storage and auth persistence will work just fine on Linux! Give it a try and let us know how it goes!

**Comment by markvideon** [comment]
> @matthewwong525 Sorry for the confusion, but you can use most of the features on Linux today actually. All that is missing is the deep link feature to bring back the user to the app once someone clicks on the confirmation email as @Vinzent03 has pointed out. Everything else from database, realtime, storage and auth persistence will work just fine on Linux! Give it a try and let us know how it goes!

I've just made a comment on that issue here: 
https://github.com/llfbandit/app_links/issues/20#issuecomment-1368711249

I've recently published [Desktop Entry](https://pub.dev/packages/desktop_entry) which includes an example Flutter project that might be helpful. As I mention in that comment, the configuration will be different depending on how the application developer is distributing their application.

**Comment by predragcvetkovski** [comment]
@dshukertjr [app_links](https://pub.dev/packages/app_links/changelog): ^3.5.0 published 22 days ago included a new feature: Linux support, which was standing in the way of supabase_flutter supporting Linux platform.

Last month I've migrated from Firebase, due to the limited platform support, and Supabase is awesome! 🚀🚀🚀 Adding Linux support is just an icing on the cake 🍥

Can we get an updated version of supabase_flutter next week?

**Comment by dshukertjr** [comment]
@predragcvetkovski Sure, we can include it in the next update on Monday. 

BTW, if app_link already supports Linux, you should already be able to use supabase_flutter in Linux as well! Make sure your app is using app_link v3.5.0, and follow the deep link set up instruction on app_link for Linux, and everything should be good!

**Comment by predragcvetkovski** [comment]
@dshukertjr thanks, I look forward to trying it out on Monday! 🚀

The app builds and runs on Linux, however when the user taps on the magiclink it opens Chrome, instead of routing back to the app to complete the auth. I will check the deep link set up instruction on app_link for Linux to make sure I haven't missed anything. 👀

**Comment by dshukertjr** [comment]
@predragcvetkovski 👍

Smash double check that you have app_link v3.5.0 it later in your pubspec.lock file!

**Comment by rickypid** [comment]
Hello everyone,

I wanted to ask a question as there is indeed Linux support but it is not stated here: https://github.com/supabase/supabase-flutter/blob/9b91ce8491a6aec35d3d59767cdff45827212fa3/packages/supabase_flutter/pubspec.yaml#L33-L38

Thanks
