### ISSUE TITLE
Closing web view when `url_launcher` is finished?

### ISSUE THREAD

**Issue by seenickcode** [supabase/supabase-flutter#28]
# Feature request

## Is your feature request related to a problem? Please describe.

It seems that when, say, authenticating with the Google provider, a webview opens using the Flutter `url_launcher` package. Users must then call `await closeWebView();` when the `onAuthenticated()` hook is called for `SupabaseAuthState`. 

## Describe the solution you'd like

Guidance on if this is the correct way to do dismiss the webview after a provider login. Ideally, a dev friendly method of dismissing it without using the above solution.

**Comment by dshukertjr** [comment]
Hi @seenickcode!

Is this about coming back to the mobile app upon signing in? In that case, you actually should not have to manually call anything in order to come back to the app if you have setup [deeplink](https://github.com/supabase/supabase-flutter#deeplink-config)

With the correct setup, the flow should be like this:

1. User taps on "Github sign in" button and browser opens up
2. User completes Github sign in
3. User is redirected to Gotrue call back page
4. Upon signing the user in, Gotrue call back page then re-redirects the user to whatever you set at `AuthOptions(redirectTo: '[DEEPLINK_URL]')`
5. With deeplink setup, opening `[DEEPLINK_URL]` will take the user back to the mobile app

Let me know if anything is unclear!
