### ISSUE TITLE
New token refresh algorithm  on gotrue-js

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase-flutter#317]
*Posting this without reading too much into the context, so might not be relevant for us, but wanted to get it out there for visibility. 

Gotrue-js is updating their token refresh algorithm, here. Might be something worth looking into!
https://github.com/supabase/gotrue-js/pull/564

Personally, I think the current implementation is okay though unless someone knows any issues.

**Comment by matthewwong525** [comment]
So my supabase app supports offline usage (through flutter) and oftentimes if I get reports of my users being automatically "logged out". This is because the refresh token has trouble actually getting a refresh once the internet connection has been restored. Anyways, my solution to this was to periodically refresh the token (before it's expired) and set the expiration date to 7 days.

**Comment by d-e-h-i-o** [comment]
Our users also get logged out sometimes. Often the following exception is thrown: 
`AuthException('Access token refresh retry limit exceeded.');`
`GoTrueClient._setTokenRefreshTimer (gotrue_client.dart:552)
GoTrueClient._callRefreshToken (gotrue_client.dart:606)`

Maybe this is expected when a short expiration time is set, and the internet connection not reliable.
