### ISSUE TITLE
Dissallowed useragent for Android auth

### ISSUE THREAD

**Issue by elliottetzkorn** [supabase/supabase-flutter#351]
**Describe the bug**
For Android auth, using the default auth provider (in app webview), google rejects the useragent with a 403 error.

**To Reproduce**
1. Set the auth provider as default
2. Launch auth from any Android device

**Expected behavior**
The webview authentication should work.

**Screenshots**

**Version (please complete the following information):**
 - 1.4.0

**Additional context**

**Comment by dshukertjr** [comment]
@elliottetzkorn 
Could you clarify what exactly you mean by `Set the auth provider as default`?

**Comment by elliottetzkorn** [comment]
I'm referring to the prop `authScreenLaunchMode`.

**Comment by dshukertjr** [comment]
@elliottetzkorn 
The default launch mode is `LaunchMode.externalApplication` and not `inAppWebview`, but could you provide a detailed step by step for reproducing the error you are experiencing including any code that you run?

**Comment by Quatton** [comment]
Hello! I believe this is an expected behaviour because Google [does](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html) prevent OAuth interactions via Web View.

In summary,

1. This is due to Google's [policies](https://developers.google.com/identity/protocols/oauth2/policies#browsers) stating that embedded browsers are prone to script/cookie injections.
2. WebView reinstantiates a new profile every time. That means the user has to input their credentials again instead of just reusing what's saved in their browser. [Recommended fixes by Google](https://developers.google.com/identity/protocols/oauth2/native-app#au(thorization-errors-disallowed-useragent))
3. If you still insist on using a web view, which is not really recommended, there is a way to set a user agent on the header. This should by-pass Google's (at least when I tried before.)

Let's by all means use a secure browser for requesting authorization.

**Comment by gabfeudo** [comment]
I’m working on it, look at my last comment here https://github.com/supabase/supabase-flutter/issues/357
