### ISSUE TITLE
Can't send broadcast messages to multiple channels

### ISSUE THREAD

**Issue by flexagoon** [supabase/supabase-flutter#382]
# Bug report

## Describe the bug

If you subscribe and send messages to two broadcast channels, neither of them receive messages

## To Reproduce

1. Subscribe to one channel and assign it to a variable
2. Subscribe to another channel (either a different channel or the same channel with a different filter) and assign it to a different variable
3. Send a broadcast message to the first channel
4. Send a broadcast message to the second channel

## Expected behavior

Subscribers of both channels receive the message

## Additional context

Code example in Dart:

```dart
void sendPing(String event, String message) {
  final channel = supabase.channel('test');
  channel.subscribe();
  channel.send(
      type: RealtimeListenTypes.broadcast,
      event: event,
      payload: {'data': message});
}

void main() {
  sendPing('test1', 'message 1');
  sendPing('test2', 'message 2');
}
```

**Comment by Yogesh-Dubey-Ayesavi** [comment]
@flexagoon  any updates on this, im also facing the same issue

**Comment by dshukertjr** [comment]
A few things to clarify here:
1. You cannot have two channels with the same channel name in the same client. 
2. In order to receive the broadcast message, you have to have the same channel name and the event name as the client that is sending the message. 

@flexagoon Your sample code [here](https://github.com/supabase/supabase-flutter/issues/382#issue-1608108778) violates the first rule, because both channels are listening to `test` channel. Follow the above rules and you should have no problem receiving the broadcast events.
