### ISSUE TITLE
misbehavior when logging in via iOS and LaunchMode.inAppWebView

### ISSUE THREAD

**Issue by bertuz** [supabase/supabase-flutter#428]
**Describe the bug**
when logging in with `authScreenLaunchMode: LaunchMode.platformDefault`, or `inAppWebView`, if the user is already logged in with the chosen provider (i.e. google) an exception is raised.

**To Reproduce**
0. listen to the auth events ```Supabase.instance.client.auth.onAuthStateChange.listen((data) {...}));```
1. sign in with ``` final success = await Supabase.instance.client.auth.signInWithOAuth(
          Provider.google,
          redirectTo: dotenv.get('SUPABASE_AUTH_CALLBACK', fallback: ''),
          authScreenLaunchMode: LaunchMode.platformDefault, context: context)```. 
2. if not logged in: the google login page is shown, the future is returned with a `success = true`
2.1. once logged in properly, the webview is stuck on google with a spinner. "done" must be pressed
2.2. the listener callback is called properly, along with the `data.session`
3. if logged in already, if a logout is called, it's performed properly. close the app and reopen it
3.1. perform the log-in as on step 1. : a blank page is shown. done must be pressed to exit the webview
3.2. an exception of raised by `signInWithOAuth` is thrown: `flutter: PlatformException(Error, Error while launching https://<project-id>.supabase.co/auth/v1/authorize?provider=google&redirect_to=net.bertamini.<my-app>%3A%2F%2Flogin-callback%2F, null, null)
`
3.3. the listener callback is called properly, along with the `data.session`

**Expected behavior**
1. `signInWithOAuth` should be returned true
2. no exceptions thrown
3. a way to close the window from code should be given

**Screenshots**
![Simulator Screenshot - iPhone 14 Pro Max - 2023-04-02 at 16 40 37](https://user-images.githubusercontent.com/3980392/229361081-31ce76fa-acd9-4818-837d-226cdb0f4c1a.png)
![Simulator Screenshot - iPhone 14 Pro Max - 2023-04-02 at 16 47 57](https://user-images.githubusercontent.com/3980392/229361083-a05f0637-c132-4668-beb2-197d3b1818e2.png)

**Version (please complete the following information):**
On Linux/macOS
```
◼ proj / $ dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"                                                                                                                         130 
├── supabase_flutter 1.6.2
│   ├── supabase 1.6.1
│   │   ├── functions_client 1.1.1
│   │   ├── gotrue 1.5.7
│   │   ├── postgrest 1.2.2
│   │   ├── realtime_client 1.0.3
│   │   ├── storage_client 1.2.5

```

**Additional context**
-

**Comment by dshukertjr** [comment]
You can use pass `LaunchMode.inAppWebView` to `authScreenLaunchMode` to perform your OAuth to make the webview close automatically. 

Feel free to reopen this issue if you cannot get it to work!

**Comment by bertuz** [comment]
@dshukertjr 🤔 `LaunchMode.inAppWebView` does work but it has a weird behavior: from the "screen" (a pushed widget) I call `Supabase.instance.client.auth.signInWithOAuth(`. Once logged in a pop is performed, and the screen itself - as well as the webview - is removed. I guess the intention was removing the pushed webview, but it's kind of called twice? is this expected or could it be me misusing it?

**Comment by dshukertjr** [comment]
> yes, but LaunchMode.platformDefault does have the problem I've described above! Not a big deal, I can use the other mode, but we'd better track it and fix it right? Have you been able to reproduce it?

This was actually the intended behavior, but as you suggest, I think it makes sense to fix it for `launchMode.platformDefault` as well. Let me fix it right now.

> inAppWebView it does work but it has a weird behavior: from the "screen" (a pushed widget) I call Supabase.instance.client.auth.signInWithOAuth(. Once logged in a pop is performed, and the screen itself - as well as the webview - is removed. I guess the intention was removing the pushed webview, but it's kind of called twice? is this expected or could it be me misusing it?

This is indeed a bug. Will fix it right now within the same PR.

**Comment by mreky** [comment]
Why does Launchmmode.inAppWebView take the entire screen instead of showing a dismissible web view? 
I have this function:
`signInWithGoogle(riverpod.WidgetRef ref, BuildContext context) async {
    try {
      final success = await supabase.auth.signInWithOAuth(Provider.google,
          authScreenLaunchMode: LaunchMode.inAppWebView,
          context: context,
          redirectTo: "<domain>://login-callback/");
      if (success) {}
    } catch (e) {
      print(e.toString());
    }
  }`
When I call the function this is the screen I get: 
<img width="405" alt="GOOGLE SIGN IN" src="https://user-images.githubusercontent.com/118037596/230783499-c056f721-e327-43fc-92a4-bf3f849ebf9e.png">
Whereas using Launchmode.platformDefault shows the correct webview but still has the permanent loading screen after login is compelete.
This is the regular screen for platformDefault(as expected)
<img width="405" alt="Screenshot 2023-04-09 at 12 04 08 PM" src="https://user-images.githubusercontent.com/118037596/230783631-5e93a330-33c5-4696-ac3f-09c12238d933.png">
And when logged in with platformDefault the screen is stuck loading:
<img width="405" alt="Screenshot 2023-04-09 at 12 06 26 PM" src="https://user-images.githubusercontent.com/118037596/230783669-c1848489-980a-460c-9b8a-477d06cf1a04.png">

The problem is inAppWebView works as expected, but has wrong webview screen unless I'm doing something wrong, and platformDefault(as mentioned by @bertuz is stuck loading after login is complete.
