### ISSUE TITLE
Need a way to access vault secrets

### ISSUE THREAD

**Issue by Wizzel1** [supabase/supabase-flutter#504]
**Is your feature request related to a problem? Please describe.**
Now that vault is in public beta, it would be great to have a way to access the stored secrets.

**Describe the solution you'd like**
It would be nice to have a `.vault` API along those lines: `Supabase.instance.client.vault.getSecret('secretname');`

**Describe alternatives you've considered**
I have tried to find a way for an alternative but I am not sure if I should create an rpc or if it is possible via postgREST API.

**Comment by dshukertjr** [comment]
@Wizzel1 
Thanks for the interest in Vault!

Actually, Vault is meant to store secrets that are used within the database so that it can talk to other systems securely, such as for [Supabase wrappers](https://supabase.github.io/wrappers/).

If you are looking for a way to encrypt the data you store on your Supabase database, you can look into [this guide](https://supabase.com/docs/guides/database/column-encryption).
