### ISSUE TITLE
Cannot run multiple Instances of Supabase Windows Desktop App

### ISSUE THREAD

**Issue by iampopal** [supabase/supabase-flutter#54]
Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a simple app and Initialize supabase app. 
2. Build a release of the app. 
3. Run 2 Instance of The app

The issue is that Supabase use a single file which Is reading by the first Instance so the second Instance of the app is not working.

**Comment by dshukertjr** [comment]
Hi @iampopal!

If you could describe in what way the app does not work, it would be very helpful. By creating two instances of the app, are you trying to sign in as different users in those apps?

**Comment by bdlukaa** [comment]
In my opinion, if the app is the same, the database should be the same

**Comment by iampopal** [comment]
@dshukertjr 
Just by opening two windows of the app. 
The second windows crashes.

**Comment by iampopal** [comment]
The database is also the same, but the file which saves database info is used by two instances and windows not allow it.

**Comment by iampopal** [comment]
Do build a release version of the app and then run 2 instances of the app, the app will crush

**Comment by iampopal** [comment]
When will we have a fix for this...

**Comment by dshukertjr** [comment]
@iampopal When you say "Supabase use a single file", which file do you mean here? Is it the hive file to persist auth?

**Comment by iampopal** [comment]
Yes Its hive files, windows allow one file for read and write.

I have fix this issue by using SecureStorage package

**Comment by dshukertjr** [comment]
@iampopal Nice! So if I'm correct, it sounds this is more like a hive issue than Supabase issue, but would you agree?

**Comment by iampopal** [comment]
Yup Tyler, It's hive Issue
But
Would be great If supabase team change the default version of hive storage

Because hive file cannot be opened in multiple instances.

Would be great to make default storage SecureStorage package

Because it's secure and can be use to open multiple instances at one time

Thank you.

**Comment by Vinzent03** [comment]
To be honest, I think using `Hive` just to store the session and refresh token is kinda overkill. Iirc, the reason for hive was the ability to store it encrypted on all platforms. Wasn't there a need to manually set an encryption key nevertheless? So it's not secured by default? But since they are meant to be stored on the client, I think `shared_preferences` or if you really want to secure them `flutter_secure_storage` is suited better.

**Comment by dshukertjr** [comment]
>To be honest, I think using Hive just to store the session and refresh token is kinda overkill. Iirc, the reason for hive was the ability to store it encrypted on all platforms. Wasn't there a need to manually set an encryption key nevertheless? So it's not secured by default? But since they are meant to be stored on the client, I think shared_preferences or if you really want to secure them flutter_secure_storage is suited better.

Yeah, Hive, shared_preferences, flutter_secure_storage all should be safe options to store access and refresh tokens and there shouldn't be any need to encrypt the tokens being stored since applications cannot access other applications' files anyway, and same goes for web. I do agree that Hive might have been a bit of overkill, but it is pretty performant compared to other options, and I fear that if we change the default storage option right now, it's going to confuse a lot of the users, but what do you think?

**Comment by cgestes** [comment]
quick tips: I copy pasted the supabase local storage and added an instanceId to Hive.initFlutter call. That way I can change the instanceId and have multiple instance of my application running.
If the app can have multiple instances, I wonder how this affect the storage if it is shared. Seems to open the door to a lot of interesting questions... should the instances authentication states be synchronized?

**Comment by dshukertjr** [comment]
@cgestes 
Oh nice! That might solve this issue then huh? How exactly did you add an instanceID to `Hive.initFlutter` call?

**Comment by Vinzent03** [comment]
This is now fixed with v2 #673, as we no longer use Hive for storing the session.
