### ISSUE TITLE
Incomplete documentation.

### ISSUE THREAD

**Issue by catalunha** [supabase/supabase-flutter#563]
According to the following images
We have good documentation for JS
![image](https://github.com/supabase/supabase-flutter/assets/19995819/8f61b94e-6647-4fe4-8403-09f8623e77cf)

But incomplete documentation for Flutter/Dart in its lib.
![image](https://github.com/supabase/supabase-flutter/assets/19995819/31948d36-8198-417b-aa4d-72d38182b2e9)

If the users DataSource were available, I could provide the complete example.

**Comment by dshukertjr** [comment]
@catalunha 
Thanks for spotting this one. Our docs is fully open sourced, and here is the file for the Flutter/ Dart docs. It would be amazing if you could contribute!

https://github.com/supabase/supabase/blob/master/spec/supabase_dart_v1.yml

**Comment by catalunha** [comment]
@dshukertjr 
Thank you for your trust even with my limited knowledge of the Supabase ecosystem. I will study this topic further.
**But where to discover all possibilities for select('???') to solve the same problems as Postgres SQLs but via library.**

**Comment by catalunha** [comment]
Possibilities are other alternatives like the initial examples:
select('cities')
select('name,cities(name)')
select('*, users!inner(*)')
etc

**Comment by dshukertjr** [comment]
>But where to discover all possibilities for select('???') to solve the same problems as Postgres SQLs but via library.

All possible case might be a stretch, but parity with the JS documentation would be good enough, I think! If we can have the same set of examples as the JS library documentation, that would be amazing!

**Comment by catalunha** [comment]
> All possible case might be a stretch, 

I agree that parity with JS is minimal.
And sorry. Perhaps the term all possibilities was not the best.
But where did variants such as:
select('name,city1:cities(name)') // 01
select('name,cities(name)') //02
select('name,city1:cities!inner(name)') //03
Because if I'm going to use a ...eq(citie1.id,'123') I can't use form 01 it generates an error. I need to use form 03 for this filter.
Did you understand ?
Would the JS source be PostgresREST?

**Comment by catalunha** [comment]
Another question.
The same parameters work for JS or Dart. Type
...select('name')... // JS
...select('name')... // Dart

**Comment by dshukertjr** [comment]
@catalunha 
>select('name,city1:cities(name)') // 01
select('name,cities(name)') //02
select('name,city1:cities!inner(name)') //03
Because if I'm going to use a ...eq(citie1.id,'123') I can't use form 01 it generates an error. I need to use form 03 for this filter.

`select('name,city1:cities(name)').eq(citie1.id,'123')` should be a valid query actually!

>Another question.
The same parameters work for JS or Dart. Type
...select('name')... // JS
...select('name')... // Dart

Yup, the same parameters should work. 

Please do not feel obligated that you need to add this documentation yourself though. I just thought if you are interested, it might be fun, but only if you have spare time and if you are willing to do so. Otherwise, we are totally happy to get it done ourselves!

**Comment by catalunha** [comment]
I like to write a lot. But my limitation in writing in English limits me to share many of my notes. Most of them being in the Brazil community for SupaBase. But I don't stop adding. It is good. It is in giving that one receives.
Let's go ahead. Count on me.

**Comment by dshukertjr** [comment]
Sure, thanks for considering to contribute though! We will take care of this one when we can!
