### ISSUE TITLE
Local storage 

### ISSUE THREAD

**Issue by CntrlX** [supabase/supabase-flutter#584]
Hive is not maintained anymore by it's author, he has moved on to another similar project called isar which is better than hive.

**Comment by dshukertjr** [comment]
Thanks for opening this issue. We do have plans of moving away from Hive and just using SharedPreferences.

**Comment by fior-di-latte** [comment]
FYI the discontinuation of Hive has been retracted by its author:
https://twitter.com/simcdev/status/1686517861060136960?s=20 
:)

**Comment by CntrlX** [comment]
He said he will be updating hive to work with isar.

**Comment by Vinzent03** [comment]
Thanks for commenting. I've read that tweet as well before your comment, but this won't change our decision to most likely move away from Hive. Some reasons are:
- doesn't work in private Firefox window, because of missing IndexedDB
- pretty heavy just to store one string for auth

I'm closing this, because we will most likely remove Hive as already described [here](https://github.com/supabase/supabase-flutter/issues/287#issuecomment-1336246821)
