### ISSUE TITLE
Ability to use ".stream" with ".useSchema"

### ISSUE THREAD

**Issue by garysm** [supabase/supabase-flutter#610]
**Is your feature request related to a problem? Please describe.**
There should be an ability to create a stream on a table while selecting a schema.  

**Describe the solution you'd like**
```dart
Supabase.instance.client.useSchema('mySchema').from('records').stream(primaryKey: ['id']);
```

**Describe alternatives you've considered**
I have been able to work around this limitation by initializing the Supabase client on a different schema, but this is not desirable if I have multiple schemas and need to switch between separate Supabase client instances.

**Comment by david-fischer** [comment]
Hey, great to see that the issue is already reported and fixed! :)

Is there already an ETA when this will be published to pub.dev?

I just tried refactoring our code base using the **useSchema** method and ran into the same problem (missing .stream). Currently we have some ugly workaround using one client per schema in parallel, but this poses other problems with an authentication related feature I am working on right now. This bugfix would save me a lot of time.

Thanks and keep up the great work!

**Comment by Vinzent03** [comment]
There is already a dev release of v2 you can try.
