### ISSUE TITLE
Offline callback

### ISSUE THREAD

**Issue by mohamadkenway** [supabase/supabase-flutter#90]
Hi
If i go to offline mode and come back online , Real Time service can detect what data inserted or updated or ... when i was offline ??

**Comment by Vinzent03** [comment]
@dshukertjr We already have the app cycle check for auth, do we want to add connection check for `stream` as well or is that too much?

**Comment by dshukertjr** [comment]
@Vinzent03 
Did you have anything in particular what this could look like?

**Comment by Vinzent03** [comment]
@dshukertjr  I don't have the time to implement this myself, but I thought about listening to the connection and if the app reconnects we refetch the table from postgrest and start listening to realtime again.

**Comment by dshukertjr** [comment]
Just wanted to come back to this issue. Currently, Supabase's real-time feature requires an internet connection in order to provide real-time data. If the device goes offline, any data that was sent to the client from the server is lost. This is a known limitation of Supabase, and we do have some attempts to solve it like [this one](https://supabase.com/blog/postgres-crdt). Until we find a proper fix for it across all Supabase producets, Supabase will remain to have a stable internet connection as a requirement. With this, I will close this issue for now.Just wanted to come back to this issue. Currently, Supabase's real-time feature requires an internet connection in order to provide real-time data. If the device goes offline, any data that was sent to the client from the server is lost. This is a known limitation of Supabase, and we do have some attempts to solve it like [this one](https://supabase.com/blog/postgres-crdt). Until we find a proper fix for it across all Supabase producets, Supabase will remain to have a stable internet connection as a requirement. With this, I will close this issue for now.

**Comment by Vinzent03** [comment]
@dshukertjr I think you have some text twice in your comment.

**Comment by dshukertjr** [comment]
😂
